// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "./prisma/schema.prisma",
  migrations: {
    path: "./prisma/migrations",
    seed: "pnpm dlx tsx --env-file=.env ./prisma/seed/index.ts",
  },
  datasource: {
    url: env("DIRECT_URL"),
  },
});
